language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: nighty

before_script:
  - travis_retry composer self-update
  - travis_retry composer install
  - mkdir -p build/logs

script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi;'

after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then CODECLIMATE_REPO_TOKEN=ca5102840082d45b819d5a90e7bfc0b44fb1ce03165d5a5b4460d489fd380c7c ./vendor/bin/test-reporter; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'

notifications:
  slack:
    secure: Un5LtrA55VMzaOKWdXPZBJPv2LdVmXZaLn72C+ZVwhtxZ1YaSt8nuNbfNxVAFZggmb3Dktv2DxFEKPmVf3uSO9GWhQ/tcdKgJaNkI/WH7sx6cx9T1CVB7moPe/8vbXF3UQsv9W5aeO7jnf3ijQMsRwY5E41CVxFdLlfEsXMOsjs=
